function atualizarContador(){const e=document.getElementById("contador-visitas");if(!e)return;let t=parseInt(localStorage.getItem("visitasSite")||"0",10);t+=1,localStorage.setItem("visitasSite",t),e.textContent=String(t).padStart(6,"0")}function iniciarCoracoesClique(){document.addEventListener("click",function(e){if(e.target.closest(".modal-overlay"))return;const t=document.createElement("div");t.textContent=["💗","💖","💕","💓"][Math.floor(4*Math.random())],t.style.position="fixed",t.style.left=e.clientX+"px",t.style.top=e.clientY+"px",t.style.fontSize="22px",t.style.pointerEvents="none",t.style.zIndex="9999",t.style.transition="all 1s ease-out",document.body.appendChild(t),requestAnimationFrame(()=>{t.style.transform="translateY(-60px) scale(1.5)",t.style.opacity="0"}),setTimeout(()=>t.remove(),1e3)})}function criarModalDOM(){if(document.getElementById("retro-modal-overlay"))return;const e=`
    <div class="modal-overlay" id="retro-modal-overlay">
      <div class="modal-box">
        <h3 id="modal-titulo">Aviso</h3>
        <p id="modal-mensagem"></p>
        <input type="text" id="modal-input" style="display:none;" placeholder="exemplo@email.com">
        <div class="modal-botoes">
          <button class="btn-retro" id="btn-modal-ok">OK</button>
          <button class="btn-retro" id="btn-modal-cancelar" style="display:none;">Cancelar</button>
        </div>
      </div>
    </div>`;document.body.insertAdjacentHTML("beforeend",e)}window.alert=function(e){criarModalDOM(),document.getElementById("modal-titulo").innerText="Aviso 💖",document.getElementById("modal-mensagem").innerText=e,document.getElementById("modal-input").style.display="none",document.getElementById("btn-modal-cancelar").style.display="none";const t=document.getElementById("retro-modal-overlay");t.style.display="flex",document.getElementById("btn-modal-ok").onclick=()=>{t.style.display="none"}};function garantirEmail(e){const t=localStorage.getItem("usuarioEmail");if(t)return void e(t);criarModalDOM(),document.getElementById("modal-titulo").innerText="Identifique-se 💌",document.getElementById("modal-mensagem").innerText="Para deixar uma marca na nossa história, digite seu e-mail:";const o=document.getElementById("modal-input");o.style.display="block",o.value="";const n=document.getElementById("btn-modal-ok"),l=document.getElementById("btn-modal-cancelar");l.style.display="inline-block";const i=document.getElementById("retro-modal-overlay");i.style.display="flex",n.onclick=()=>{const t=o.value.trim(),n=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;t?n.test(t)?(localStorage.setItem("usuarioEmail",t),i.style.display="none",e(t)):alert("Opa! Parece que esse e-mail não é válido.\nTente algo como: nome@email.com"):alert("Precisamos saber quem é você para salvar!")},l.onclick=()=>{i.style.display="none"}}document.addEventListener("DOMContentLoaded",function(){atualizarContador(),iniciarCoracoesClique()});